#!/bin/bash
#
# backend.sh — shared non-UI backend for steamos-build.sh
#
# This file owns build/flash policy and orchestration.  Frontends should call
# it with named arguments only; do not add user-facing positional parameters.
#
# Normally invoked via steamos-build.sh; can also be called directly:
#   sudo ./lib/backend.sh --action build --image /home/image/steamdeck-repair.img.bz2
#   sudo ./lib/backend.sh --action flash --image /home/image/foo-nvidia-usbinstall.img \
#        --device /dev/sda --confirm
#   ./lib/backend.sh --action list-images
#   ./lib/backend.sh --action list-devices

set -euo pipefail

BACKEND_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_DIR="$(cd "$BACKEND_DIR/.." && pwd)"
PROJECT_DIR="$SCRIPT_DIR"

# ---------------------------------------------------------------------------
# Structured logging — must be available before arg parsing.
# ---------------------------------------------------------------------------
# shellcheck source=lib/logging.sh
source "$BACKEND_DIR/logging.sh"

# ---------------------------------------------------------------------------
# Defaults shared by CLI + GUI.
# ---------------------------------------------------------------------------
: "${ACTION:=}"
: "${IMG:=}"
: "${TARGET_DEV:=}"
: "${CONFIG_FILE:=}"
: "${PARTSET:=}"

UPDATE_MODE="selfheal" # selfheal | hold | stock
# shellcheck disable=SC2034  # consumed by lib/finalize.sh and lib/installer.sh
ADD_INSTALLER=1
: "${HW_SUPPORT_ITEMS:=}"  # space-separated items: linux-firmware libfprint fprintd bolt dkms
DEFAULT_SESSION="game"     # desktop | game
: "${INITRAMFS_MODULES:=}" # space-separated module list; empty = stock
: "${GAMING_ITEMS:=}"      # space-separated: (all items now handled by optimization system)
# shellcheck disable=SC2034  # consumed by lib/common_drivers.sh, lib/finalize.sh, and lib/flashless.sh
TARGET_VARIANT="steamdeck" # steamdeck | steamdeck-oobe
UPDATE_BRANCH="stable"     # stable | beta | preview | rc | bc | pc | main
PACMAN_REPO="valve"        # valve | main
BASE_OS_MODE="additive"    # additive | upgrade
: "${ROOTFS_SIZE:=}"
: "${OUTPUT_DIR:=}" # empty = same directory as source image
: "${WORKDIR:=}"
WORKDIR_LOCATION="auto" # auto | ram | disk
: "${_WORKDIR_EXPLICIT:=}"

FLASH_CONFIRMED=0
ALLOW_SYSTEM_DISK=0
: "${CLEANUP_RUN_ID:=}"
CLEANUP_PURGE=0
: "${BUILD_ID:=}" # shared build directory ID; generated by frontend if empty

# Build-time globals expected by sourced libraries.
: "${OUT:=}"
: "${OUT_FINAL:=}"
: "${IMG_BASE:=}"
: "${LOOPDEV:=}"
# shellcheck disable=SC2034
UDEV_RULE=/run/udev/rules.d/89-steamos-build-installer.rules
UPSTREAM_DRIVER_REF="${UPSTREAM_DRIVER_REF:-}"

_backend_usage() {
  cat "$(heredoc_dir)/static/usage-backend.txt"
}

# ---------------------------------------------------------------------------
# Argument parsing.  Config is loaded first, then explicit args override it.
# ---------------------------------------------------------------------------
# shellcheck disable=SC2034
args=("$@")
for ((i = 0; i < ${#args[@]}; i++)); do
  if [[ "${args[$i]}" == "--config" ]]; then
    [[ $((i + 1)) -lt ${#args[@]} ]] || {
      log_error args arg-error "--config requires a value"
      exit 2
    }
    CONFIG_FILE="${args[$((i + 1))]}"
    break
  fi
done

if [[ -n "$CONFIG_FILE" ]]; then
  [[ -f "$CONFIG_FILE" ]] || {
    log_error args arg-error "Config file not found: $CONFIG_FILE"
    exit 2
  }
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

# shellcheck disable=SC2034
# shellcheck source=lib/args.sh
source "$BACKEND_DIR/args.sh"

while [[ $# -gt 0 ]]; do
  if parse_common_arg "$1" "${2:-}"; then
    shift "$_ARG_SHIFT"
    continue
  fi

  case "$1" in
    --confirm)
      FLASH_CONFIRMED=1
      shift
      ;;
    --partset)
      [[ $# -ge 2 ]] || {
        log_error args arg-error "--partset requires a value"
        exit 2
      }
      PARTSET="$2"
      export PARTSET
      shift 2
      ;;
    --run-id)
      [[ $# -ge 2 ]] || {
        log_error args arg-error "--run-id requires a value"
        exit 2
      }
      CLEANUP_RUN_ID="$2"
      shift 2
      ;;
    --purge)
      CLEANUP_PURGE=1
      shift
      ;;
    -h | --help)
      _backend_usage
      exit 0
      ;;
    --)
      shift
      [[ $# -eq 0 ]] || {
        log_error args arg-error "Positional parameters are not supported."
        exit 2
      }
      ;;
    *)
      log_error args arg-error "Unknown argument: $1"
      _backend_usage >&2
      exit 2
      ;;
  esac
done

[[ -n "$ACTION" ]] || {
  log_error args arg-error "--action is required"
  _backend_usage >&2
  exit 2
}

# ---------------------------------------------------------------------------
# Shared flash backend.
# ---------------------------------------------------------------------------
_load_flash_libs() {
  # shellcheck source=lib/common.sh
  source "$BACKEND_DIR/common.sh"
  # shellcheck source=lib/protected.sh
  source "$BACKEND_DIR/protected.sh"
  # shellcheck source=lib/mounts.sh
  source "$BACKEND_DIR/mounts.sh"
  # shellcheck source=lib/flash.sh
  source "$BACKEND_DIR/flash.sh"
  # shellcheck source=lib/pipeline.sh
  source "$BACKEND_DIR/pipeline.sh"
  # shellcheck source=lib/pipelines/pipeline_flash.sh
  source "$BACKEND_DIR/pipelines/pipeline_flash.sh"
}

_flash_image_is_complete() {
  local image="$1"
  [[ -f "$image" && -f "${image}.build-complete" ]]
}

_flash_discover_images() {
  # During the current transition, RAM output is still a legitimate completed
  # location.  Once build publication is made canonical, remove /dev/shm here.
  local search_dirs=(
    "$PROJECT_DIR"
    "/home/image"
    "/dev/shm/steamos-build"
    "$HOME/Downloads"
  )
  [[ -n "${OUTPUT_DIR:-}" ]] && search_dirs+=("$OUTPUT_DIR")
  local d f
  local -a found=()

  for d in "${search_dirs[@]}"; do
    [[ -d "$d" ]] || continue
    while IFS="" read -r f; do
      [[ -n "$f" ]] || continue
      _flash_image_is_complete "$f" || continue
      found+=("$(readlink -f "$f")")
    done < <(find "$d" -maxdepth 1 -name '*nvidia*usbinstall*.img' -type f 2>/dev/null)
  done

  ((${#found[@]})) || return 0

  # TSV: path, location, human size, modified epoch, modified display
  local _sorted
  _sorted="$(printf '%s\n' "${found[@]}" | sort -u)"
  while IFS="" read -r f; do
    local where
    case "$f" in
      /dev/shm/*) where="RAM build" ;;
      /home/image/*) where="Persistent output" ;;
      "$PROJECT_DIR"/*) where="Project output" ;;
      *) where="Other" ;;
    esac
    printf '%s\t%s\t%s\t%s\t%s\n' \
      "$f" \
      "$where" \
      "$(du -h "$f" | cut -f1)" \
      "$(stat -c '%Y' "$f")" \
      "$(date -r "$f" '+%Y-%m-%d %H:%M:%S')"
  done <<<"$_sorted" | sort -t$'\t' -k4,4nr
}

_flash_validate_image() {
  local image="$1"
  [[ -f "$image" ]] || {
    log_error flash validation-error "Image not found: $image"
    return 1
  }

  if [[ "$(basename "$image")" == *nvidia*usbinstall*.img ]] && ! _flash_image_is_complete "$image"; then
    log_error flash validation-error "Refusing NVIDIA installer image without .build-complete marker: $image"
    return 1
  fi
}

_backend_flash() {
  [[ $EUID -eq 0 ]] || {
    log_error flash validation-error "Flash action requires root."
    exit 1
  }
  [[ "$FLASH_CONFIRMED" -eq 1 ]] || {
    log_error flash validation-error "Flash is destructive. Re-run with --confirm after the user has confirmed the target."
    exit 2
  }
  [[ -n "$IMG" ]] || {
    log_error flash validation-error "--image is required for flash"
    exit 2
  }
  [[ -n "$TARGET_DEV" ]] || {
    log_error flash validation-error "--device is required for flash"
    exit 2
  }

  IMG="$(readlink -f "$IMG")"
  _flash_validate_image "$IMG"
  [[ -b "$TARGET_DEV" ]] || {
    log_error flash validation-error "Not a block device: $TARGET_DEV"
    exit 1
  }

  if [[ "$ALLOW_SYSTEM_DISK" -ne 1 ]] && flash_is_system_disk "$TARGET_DEV"; then
    log_error flash validation-error "Refusing to flash the current system disk: $TARGET_DEV"
    log_error flash validation-error "Use --allow-system-disk only if this has been explicitly verified."
    exit 1
  fi

  # Acquire workspace-level lock to prevent concurrent operations
  if ! workspace_lock_acquire; then
    die "Another build/cleanup/flash is running — cannot proceed"
  fi
  trap 'workspace_lock_release 2>/dev/null || true' EXIT

  register_flash_pipeline
  run_pipeline || {
    log_error flash pipeline-error "Flash pipeline failed."
    exit 1
  }
}

# ---------------------------------------------------------------------------
# Shared build backend.  This is the former steamos-build-installer.sh build
# orchestration moved out of the frontend.
# ---------------------------------------------------------------------------
_load_build_libs() {
  # Source library loader and pipeline
  # shellcheck source=lib/library-loader.sh
  source "$BACKEND_DIR/library-loader.sh"

  # Source pipeline definition
  # shellcheck source=lib/pipelines/pipeline_build.sh
  source "$BACKEND_DIR/pipelines/pipeline_build.sh"

  # Load all build workflow libraries
  load_workflow_libs "build" "$BACKEND_DIR"
}

_check_build_deps() {
  if [[ -f "$BACKEND_DIR/check-deps.sh" ]]; then
    bash "$BACKEND_DIR/check-deps.sh" --check-only || exit 1
    return 0
  fi

  local missing=()
  local cmd
  for cmd in losetup blkid btrfs bzip2 gzip xz pv rsync curl depmod sed awk tar zstd pacman pactree python3 readelf sgdisk sfdisk; do
    # lint-ignore: silenced-stdout — command -v output (path) is intentionally discarded; only exit code is used
    command -v "$cmd" >/dev/null || missing+=("$cmd")
  done

  if [[ ${#missing[@]} -gt 0 ]]; then
    local pkgs=()
    for cmd in "${missing[@]}"; do
      case "$cmd" in
        btrfs) pkgs+=(btrfs-progs) ;;
        readelf) pkgs+=(binutils) ;;
        depmod) pkgs+=(kmod) ;;
        pactree) pkgs+=(pacman-contrib) ;;
        sgdisk) pkgs+=(gptfdisk) ;;
        *) pkgs+=("$cmd") ;;
      esac
    done
    mapfile -t pkgs < <(printf "%s\n" "${pkgs[@]}" | sort -u)
    die "Missing host tools: ${missing[*]}. Install with: pacman -S ${pkgs[*]}"
  fi
}

_normalize_build_options() {

  [[ -z "$ROOTFS_SIZE" || "$ROOTFS_SIZE" =~ ^[0-9]+[KMGkmg]?$ ]] \
    || die "--rootfs-size takes a size like 10G, 10240M, or 10240 (plain = MiB)"

  case "$DEFAULT_SESSION" in
    "" | desktop | game) ;;
    *) die "--session must be desktop or game" ;;
  esac

  case "$WORKDIR_LOCATION" in
    auto | ram | disk) ;;
    *) die "--workdir-location must be auto, ram, or disk" ;;
  esac

  case "$UPDATE_MODE" in
    selfheal | hold | stock) ;;
    *) die "Invalid update mode: $UPDATE_MODE" ;;
  esac

  case "$BASE_OS_MODE" in
    additive | upgrade) ;;
    *) die "Invalid base OS mode: $BASE_OS_MODE" ;;
  esac

  if [[ -n "$ROOTFS_SIZE" ]]; then
    case "${ROOTFS_SIZE: -1}" in
      G | g) ROOTFS_SIZE=$((${ROOTFS_SIZE%[Gg]} * 1024)) ;;
      M | m) ROOTFS_SIZE="${ROOTFS_SIZE%[Mm]}" ;;
      K | k) ROOTFS_SIZE=$((${ROOTFS_SIZE%[Kk]} / 1024)) ;;
    esac
    ((ROOTFS_SIZE > 0)) || die "--rootfs-size must be positive"
  fi
}

_resolve_build_image() {
  if [[ -n "$IMG" ]]; then
    [[ -f "$IMG" ]] || die "Image not found: $IMG"
    IMG="$(realpath "$IMG")"
    return 0
  fi

  local -a candidates=()
  mapfile -t candidates < <(
    find "$PROJECT_DIR" -maxdepth 1 \
      \( -name '*.img' -o -name '*.img.bz2' -o -name '*.img.gz' -o -name '*.img.xz' -o -name '*.img.zst' \) \
      ! -name '*-nvidia*' | sort
  )

  case ${#candidates[@]} in
    0) die "No source image specified with --image and none was found beside the script." ;;
    1)
      IMG="$(realpath "${candidates[0]}")"
      log "Auto-detected image: $IMG"
      ;;
    *) die "Multiple source images found; pass one explicitly with --image." ;;
  esac
}

_backend_build() {
  [[ $EUID -eq 0 ]] || die "Build action requires root."

  _load_build_libs

  # Initialize structured logging.
  mkdir -p "/home/.steamos-build/logs/${BUILD_ID}"
  local _console_level="info"
  if ((DEBUG)); then
    _console_level="debug"
  elif ((VERBOSE)); then
    _console_level="debug"
  fi

  log_init \
    --log-file "/home/.steamos-build/logs/${BUILD_ID}/run.jsonl" \
    --console-level "$_console_level"

  # ── Failure context functions ────────────────────────────────────────────
  _build_failure_journal_context() {
    printf "img='%s' kver='%s' step='%s'\n" \
      "$(basename "${IMG:-unknown}")" \
      "${KVER:-unknown}" \
      "${CURRENT_STEP:-unknown}"
  }

  _build_failure_snapshot_extra() {
    # ── Build configuration ──────────────────────────────────────────────
    log_debug build failure-snapshot "BUILD CONFIGURATION"
    log_info build failure-config \
      "Build config" \
      img "${IMG:-unknown}" \
      out "${OUT:-unknown}" \
      workdir "${WORKDIR:-unknown}" \
      rootfs_size "${ROOTFS_SIZE:-unknown}" \
      kver "${KVER:-unknown}" \
      base_os_mode "${BASE_OS_MODE:-unknown}" \
      update_mode "${UPDATE_MODE:-unknown}" || true

    # ── Workspace disk space ─────────────────────────────────────────────
    log_debug build failure-snapshot "WORKSPACE DISK SPACE"
    if [[ -n "${WORKDIR:-}" ]]; then
      df -h "$WORKDIR" 2>&1 | log_capture_stream build debug workspace-disk || true
      du -sh "$WORKDIR" 2>&1 | log_capture_stream build debug workspace-usage || true
    fi

    # ── Source image info ────────────────────────────────────────────────
    log_debug build failure-snapshot "SOURCE IMAGE"
    if [[ -n "${IMG:-}" && -e "${IMG:-}" ]]; then
      # shellcheck disable=SC2012  # diagnostic output, not parsed
      ls -lh "$IMG" 2>&1 | log_capture_stream build debug source-image || true
    fi
    lsblk 2>&1 | log_capture_stream build debug block-devices || true

    # ── Rootfs mount state ───────────────────────────────────────────────
    if [[ -n "${MNT:-}" ]] && mountpoint -q "$MNT" 2>/dev/null; then
      log_debug build failure-snapshot "ROOTFS MOUNT STATE"
      findmnt "$MNT" 2>&1 | log_capture_stream build debug rootfs-mount || true
      btrfs filesystem usage "$MNT" 2>&1 | log_capture_stream build debug rootfs-usage || true
      df -h "$MNT" 2>&1 | log_capture_stream build debug rootfs-disk || true
    fi

    # ── Overlay state ────────────────────────────────────────────────────
    if [[ -n "${MERGED:-}" ]] && mountpoint -q "$MERGED" 2>/dev/null; then
      log_debug build failure-snapshot "OVERLAY STATE"
      findmnt "$MERGED" 2>&1 | log_capture_stream build debug overlay-mount || true
      df -h "$MERGED" 2>&1 | log_capture_stream build debug overlay-disk || true
    fi

    # ── Package state ────────────────────────────────────────────────────
    local _hw_new_pkgs_file="${WORKDIR:-}/hw-new-pkgs.txt"
    if [[ -n "${WORKDIR:-}" && -f "$_hw_new_pkgs_file" ]]; then
      log_debug build failure-snapshot "PACKAGE STATE"
      local _total _new _removed
      _total="$(wc -l <"$_hw_new_pkgs_file" 2>/dev/null || echo 0)"
      _new="$(grep -c '^+' "$_hw_new_pkgs_file" 2>/dev/null || echo 0)"
      _removed="$(grep -c '^-[^-]' "$_hw_new_pkgs_file" 2>/dev/null || echo 0)"
      log_info build failure-packages \
        "Package counts" \
        total "$_total" \
        new "$_new" \
        removed "$_removed" || true
      head -20 "$_hw_new_pkgs_file" 2>&1 | log_capture_stream build debug package-list || true
    fi

    # ── Driver state ─────────────────────────────────────────────────────
    if [[ -n "${MERGED:-}" ]] && mountpoint -q "$MERGED" 2>/dev/null \
      && [[ -n "${KVER:-}" ]]; then
      log_debug build failure-snapshot "DRIVER STATE"
      chroot "$MERGED" dkms status 2>&1 | log_capture_stream build debug driver-dkms || true
      chroot "$MERGED" pacman -Q nvidia-utils 2>&1 | log_capture_stream build debug driver-nvidia-utils || true
    fi
  }

  failure_journal_context() { _build_failure_journal_context; }    # lint-ignore: no-shadow
  failure_snapshot_extra() { _build_failure_snapshot_extra "$@"; } # lint-ignore: no-shadow

  _normalize_build_options
  _resolve_build_image
  _check_build_deps

  [[ "$(basename "$IMG")" != *-nvidia* ]] \
    || die "Input looks like an already-patched image — start from the clean repair image."

  IMG_BASE="${IMG%.bz2}"
  IMG_BASE="${IMG_BASE%.gz}"
  IMG_BASE="${IMG_BASE%.xz}"
  IMG_BASE="${IMG_BASE%.zst}"

  local out_basename="${IMG_BASE%.img}-nvidia-usbinstall.img"
  out_basename="$(basename "$out_basename")"

  # Output directory: explicit OUTPUT_DIR, or same directory as source image.
  if [[ -n "${OUTPUT_DIR:-}" ]]; then
    mkdir -p "$OUTPUT_DIR"
    OUT_FINAL="$OUTPUT_DIR/$out_basename"
  else
    OUT_FINAL="$(dirname "$IMG_BASE")/$out_basename"
  fi
  OUT="${OUT_FINAL}.building"

  [[ -n "$WORKDIR" ]] || WORKDIR="$(dirname "$OUT")/.nvidia-usb-work"

  # shellcheck disable=SC2034
  LOOPDEV=""
  local _trap_rc
  local _cleanup_done=0
  mkdir -p /home/.steamos-build/logs
  # shellcheck disable=SC2154  # _remaining is declared inside trap string
  trap '_trap_rc=$?; trap - EXIT; set +e; log_close 2>/dev/null || true; if [[ "${_cleanup_done:-0}" -eq 0 ]]; then
  if ! cleanup_check_host_namespace; then
    warn "EXIT trap: init namespace detected — refusing unsafe cleanup"
    warn "  Build may have lost its namespace; manual cleanup may be required"
    _trap_rc=1
  else
    cleanup_stop_background_jobs
    cleanup_remove_udev_rules
    persist_debug_logs 2>/dev/null || true
    _trap_cleanup_rc=0
    overlay_cleanup 2>/dev/null || _trap_cleanup_rc=1
    cleanup_environment 2>/dev/null || _trap_cleanup_rc=1
    if ((_trap_cleanup_rc != 0)); then
      warn "EXIT trap: cleanup failed — workspace may need manual cleanup"
      _trap_rc=1
    fi
    _remaining=""
    _remaining="$(findmnt -rno TARGET,SOURCE,FSTYPE 2>/dev/null | grep -v "^/dev\|^proc\|^sys\|^run\|^tmp\|^home\|^root\|^opt\|^nix\|^srv\|^efi\|^esp" | grep -v "^-")"
    if [[ -n "$_remaining" ]]; then
      warn "Remaining mounts after cleanup:"
      warn "$_remaining"
    fi
  fi
fi; workspace_lock_release 2>/dev/null || true; exit "$_trap_rc"' EXIT

  : "${UPSTREAM_DRIVER_REF:=master}"
  # shellcheck disable=SC2034
  UPSTREAM_DRIVER_SRC_BASE="https://raw.githubusercontent.com/torvalds/linux/$UPSTREAM_DRIVER_REF/drivers/hid"

  # Log mount namespace proof — verifies unshare isolation is active.
  log_info system mount_namespace "Build mount namespace: $(readlink /proc/self/ns/mnt 2>/dev/null || echo '<unknown>')"
  log_info system mount_propagation "Root mount propagation: $(findmnt -no PROPAGATION / 2>/dev/null || echo '<unknown>')"

  log_info build start "Starting steamos-build build (rootfs=${ROOTFS_SIZE:-5120}M)"

  # Acquire workspace-level lock to prevent concurrent operations
  if ! workspace_lock_acquire; then
    die "Another build/cleanup/flash is running — cannot proceed"
  fi

  # Ledger: recover from previous run, then initialize
  # shellcheck disable=SC2119  # pipeline_recover uses default state_root
  pipeline_recover || warn "Ledger recovery failed — proceeding without crash recovery"
  pipeline_init "" "$WORKDIR" || warn "Ledger initialization failed — proceeding without crash recovery"

  # Register and run the build pipeline
  register_build_pipeline
  if ! run_pipeline; then
    die "Build pipeline failed"
  fi
}

# ---------------------------------------------------------------------------
# Validate backend — image mounting and cleanup
# ---------------------------------------------------------------------------

VALIDATE_MNT=""
VALIDATE_LOOP=""
VALIDATE_ROOTFS=""
VALIDATE_VARPART=""
VALIDATE_UDEV_RULE="/run/udev/rules.d/89-steamos-validate.rules"

_validate_mount_image() {
  local img="$1"

  # Install udev guard BEFORE attaching loop — prevents udisks2 from
  # seeing the partitions and triggering an automount popup.
  mkdir -p /run/udev/rules.d
  cat "$(heredoc_dir)/static/validate-udev.rule" >"$VALIDATE_UDEV_RULE"
  run_dangerous_cmd udevadm control --reload-rules
  log "Installed udev guard: $VALIDATE_UDEV_RULE"

  log "Attaching loop device: $img"
  VALIDATE_LOOP="$(losetup -f --show --partscan "$img")" \
    || die "Failed to attach loop device"
  cleanup_track_loop "$VALIDATE_LOOP" "$img" "validate image"
  log "  Loop: $VALIDATE_LOOP"
  run_dangerous_cmd udevadm settle --timeout=10

  log "Scanning partitions on $VALIDATE_LOOP"
  local part label
  for part in "$VALIDATE_LOOP"p*; do
    label="$(blkid -s PARTLABEL -o value "$part" 2>/dev/null)" || continue
    log "  $part: ${label:-<unknown>}"
    case "$label" in
      rootfs-A | rootfs) VALIDATE_ROOTFS="$part" ;;
      var-A | var) VALIDATE_VARPART="$part" ;;
    esac
  done

  [[ -n "$VALIDATE_ROOTFS" ]] || die "No rootfs partition found in $img"
  log "  rootfs: $VALIDATE_ROOTFS"
  log "  var:    ${VALIDATE_VARPART:-<not found>}"

  log "Mounting $VALIDATE_ROOTFS on $VALIDATE_MNT (read-only)"
  cleanup_set_workspace "$VALIDATE_MNT" 2>/dev/null || true
  cleanup_track_tempdir "$VALIDATE_MNT" "validate workspace" || true
  cleanup_mount "$VALIDATE_MNT" "validate rootfs" -- -o ro "$VALIDATE_ROOTFS" \
    || die "Failed to mount rootfs"

  # Mount var if it exists as a separate partition.
  # Recovery images may have var baked into rootfs; skip if not found.
  if [[ -n "$VALIDATE_VARPART" ]]; then
    mkdir -p "$VALIDATE_MNT/var"
    log "Mounting $VALIDATE_VARPART on $VALIDATE_MNT/var (read-only)"
    cleanup_mount "$VALIDATE_MNT/var" "validate var" -- -o ro "$VALIDATE_VARPART" \
      || die "Failed to mount var"
  fi

  log "Mount complete"
}

_validate_cleanup() {
  local _had_e=0
  [[ -o errexit ]] && _had_e=1
  set +e
  # Unmount all tracked mounts in reverse order (var before rootfs-A)
  cleanup_unmount_registered 2>/dev/null || true
  if [[ -n "${VALIDATE_LOOP:-}" ]]; then
    strict_detach_loop "$VALIDATE_LOOP"
  fi
  if declare -F cleanup_verify >/dev/null 2>&1; then
    cleanup_verify || warn "Validate cleanup: verification detected issues"
  fi
  [[ -d "$VALIDATE_MNT" ]] && rmdir "$VALIDATE_MNT" 2>/dev/null
  # Remove udev guard and reload
  if [[ -n "${VALIDATE_UDEV_RULE:-}" ]]; then
    log "_validate_cleanup: removing udev rule $VALIDATE_UDEV_RULE"
    rm -f "$VALIDATE_UDEV_RULE" 2>/dev/null
    log "_validate_cleanup: reloading host udev rules (udevadm control --reload-rules)"
    if ! run_dangerous_cmd udevadm control --reload-rules 2>/dev/null; then
      warn "_validate_cleanup: udevadm control --reload-rules failed"
    fi
  else
    log_debug pipeline cleanup "_validate_cleanup: VALIDATE_UDEV_RULE is unset; skipping udev cleanup"
  fi
  [[ "$_had_e" -eq 1 ]] && set -e
}

_backend_validate() {
  # shellcheck source=lib/library-loader.sh
  source "$BACKEND_DIR/library-loader.sh"
  load_workflow_libs "validate" "$BACKEND_DIR"

  # Source the validate pipeline
  # shellcheck source=lib/pipelines/pipeline_validate.sh
  source "$BACKEND_DIR/pipelines/pipeline_validate.sh"

  # Pass config via environment for the pipeline to read
  export VALIDATE_CONFIG="${CONFIG_FILE:-}"

  if [[ -n "$IMG" ]]; then
    # ── Offline image validation ──────────────────────────────────────
    [[ $EUID -eq 0 ]] || die "Image validation requires root (needed for loop/mount)."
    [[ -f "$IMG" ]] || die "Image not found: $IMG"
    IMG="$(readlink -f "$IMG")"

    VALIDATE_MNT="$(mktemp -d /tmp/steamos-validate.XXXXXX)"

    trap '_validate_cleanup' EXIT

    log "=== Mounts before ==="
    local _loop_state
    _loop_state="$(losetup -a 2>/dev/null)" || true
    if [[ -n "$_loop_state" ]]; then
      log "$_loop_state"
    else
      log "  (no active loop devices)"
    fi

    _validate_mount_image "$IMG"

    export VALIDATE_ROOT="$VALIDATE_MNT"
    export MERGED="$VALIDATE_MNT"
    export OPT_MODE="chroot"
    export OPT_ROOT="$VALIDATE_MNT"

    log " "
    log "╔═══════════════════════════════════════════════════════════╗"
    log "║  VALIDATING OFFLINE IMAGE                                ║"
    log "╠═══════════════════════════════════════════════════════════╣"
    log "║  Image:    $IMG"
    log "║  Rootfs:   $VALIDATE_ROOTFS"
    log "║  Var:      ${VALIDATE_VARPART:-<not separate>}"
    log "║  Mount:    $VALIDATE_MNT"
    log "║  Mode:     chroot"
    log "╚═══════════════════════════════════════════════════════════╝"
    log " "
  else
    # ── Live system validation ────────────────────────────────────────
    export VALIDATE_ROOT="${VALIDATE_ROOT:-/}"

    log " "
    log "╔═══════════════════════════════════════════════════════════╗"
    log "║  VALIDATING LIVE SYSTEM                                  ║"
    log "╠═══════════════════════════════════════════════════════════╣"
    log "║  Root:     $VALIDATE_ROOT"
    log "║  Mode:     live"
    log "╚═══════════════════════════════════════════════════════════╝"
    log " "
  fi

  # Initialize structured logging.
  mkdir -p "/home/.steamos-build/logs/${BUILD_ID}"
  local _console_level="info"
  if ((DEBUG)); then
    _console_level="debug"
  elif ((VERBOSE)); then
    _console_level="debug"
  fi

  log_init \
    --log-file "/home/.steamos-build/logs/${BUILD_ID}/validate.jsonl" \
    --console-level "$_console_level"

  register_validate_pipeline
  local rc=0
  run_pipeline || rc=$?

  # Run cleanup before reporting final state
  if [[ -n "$VALIDATE_MNT" ]]; then
    _validate_cleanup
    trap - EXIT
  fi

  if [[ -n "$VALIDATE_MNT" ]]; then
    log " "
    log "=== Mounts after ==="
    local _loop_after
    _loop_after="$(losetup -a 2>/dev/null)" || true
    if [[ -n "$_loop_after" ]]; then
      log "$_loop_after"
    else
      log "  (no active loop devices)"
    fi
  fi

  return "$rc"
}

_backend_live() {
  [[ $EUID -eq 0 ]] || die "Live configuration requires root."

  [[ -n "$CONFIG_FILE" ]] || die "--config is required for live configuration"
  [[ -f "$CONFIG_FILE" ]] || die "Config file not found: $CONFIG_FILE"
  # shellcheck source=/dev/null
  source "$CONFIG_FILE"

  # Validate config values (same checks as build)
  case "${DEFAULT_SESSION:-}" in
    "" | desktop | game) ;;
    *) die "Invalid session: $DEFAULT_SESSION" ;;
  esac

  case "${UPDATE_MODE:-selfheal}" in
    selfheal | hold | stock) ;;
    *) die "Invalid update mode: $UPDATE_MODE" ;;
  esac

  case "${BASE_OS_MODE:-additive}" in
    additive | upgrade) ;;
    *) die "Invalid base OS mode: $BASE_OS_MODE" ;;
  esac

  _load_build_libs
  # shellcheck source=/dev/null
  source "$BACKEND_DIR/pipelines/pipeline_live.sh"

  # Acquire workspace-level lock to prevent concurrent operations
  if ! workspace_lock_acquire; then
    die "Another build/cleanup/flash is running — cannot proceed"
  fi

  # Ledger: recover from previous run, then initialize
  local _live_workdir="/dev/shm/steamos-build-live-$$"
  mkdir -p "$_live_workdir" 2>/dev/null || true
  # shellcheck disable=SC2119  # pipeline_recover uses default state_root
  pipeline_recover || warn "Ledger recovery failed — proceeding without crash recovery"
  pipeline_init "" "$_live_workdir" || warn "Ledger initialization failed — proceeding without crash recovery"

  local _live_tmpdir="/tmp/steamos-live-$$"
  mkdir -p "$_live_tmpdir"
  cleanup_set_workspace "$_live_tmpdir" 2>/dev/null || true

  # Register cleanup trap (mirrors _backend_build pattern)
  local _trap_rc
  local _cleanup_done=0
  trap '_trap_rc=$?; trap - EXIT; set +e; if [[ "${_cleanup_done:-0}" -eq 0 ]]; then
  if ! cleanup_check_host_namespace; then
    warn "EXIT trap: init namespace detected — refusing unsafe cleanup"
    warn "  Build may have lost its namespace; manual cleanup may be required"
    _trap_rc=1
  else
    cleanup_stop_background_jobs
    cleanup_remove_udev_rules
    _trap_cleanup_rc=0
    overlay_cleanup 2>/dev/null || _trap_cleanup_rc=1
    cleanup_environment 2>/dev/null || _trap_cleanup_rc=1
    if ((_trap_cleanup_rc != 0)); then
      warn "EXIT trap: cleanup failed — workspace may need manual cleanup"
      _trap_rc=1
    fi
    persist_debug_logs 2>/dev/null || true
  fi
fi; workspace_lock_release 2>/dev/null || true; exit "$_trap_rc"' EXIT

  register_live_pipeline
  if ! run_pipeline; then
    exit 1
  fi
  local _live_cleanup_rc=0
  cleanup_environment || _live_cleanup_rc=1
  _cleanup_done=1
  trap - EXIT
  workspace_lock_release 2>/dev/null || true
  if ((_live_cleanup_rc != 0)); then
    warn "cleanup_environment failed on live build — workspace may need manual cleanup"
    return 1
  fi
}

_backend_flashless() {
  [[ $EUID -eq 0 ]] || die "Flashless install requires root."
  [[ -n "$IMG" ]] || die "--image is required for flashless install"
  [[ -f "$IMG" ]] || die "Image not found: $IMG"
  IMG="$(readlink -f "$IMG")"

  # Source library loader and load the flashless workflow libs
  # shellcheck source=lib/library-loader.sh
  source "$BACKEND_DIR/library-loader.sh"
  # shellcheck source=lib/pipelines/pipeline_flashless.sh
  source "$BACKEND_DIR/pipelines/pipeline_flashless.sh"
  load_workflow_libs "flashless" "$BACKEND_DIR"

  # Workspace — use a flashless-specific subdirectory (not /tmp itself,
  # which is a system path that cleanup_set_workspace may refuse).
  local _flash_ws="/tmp/steamos-flashless-$$"
  mkdir -p "$_flash_ws" 2>/dev/null || true
  cleanup_set_workspace "$_flash_ws" 2>/dev/null || true

  # Acquire workspace-level lock to prevent concurrent operations
  if ! workspace_lock_acquire; then
    die "Another build/cleanup/flash is running — cannot proceed"
  fi

  # Ledger: recover from previous run, then initialize
  # shellcheck disable=SC2119  # pipeline_recover uses default state_root
  pipeline_recover || warn "Ledger recovery failed — proceeding without crash recovery"
  pipeline_init "" "/home/.steamos-build" || warn "Ledger initialization failed — proceeding without crash recovery"

  # Register cleanup and pipeline
  register_flashless_cleanup
  register_flashless_pipeline

  # Chain lock release into the EXIT trap that register_flashless_cleanup just set.
  local _existing_exit_trap
  _existing_exit_trap="$(trap -p EXIT | sed "s/^trap -- '//;s/' EXIT$//")"
  # shellcheck disable=SC2064  # intentional: expand _existing_exit_trap at set-time for trap chaining
  trap "${_existing_exit_trap:+$_existing_exit_trap; }workspace_lock_release 2>/dev/null || true" EXIT

  # Run
  if run_pipeline; then
    log "=== Flashless install complete — slot $FL_TARGET is ready ==="

    local out
    if out="$(steamos-bootconf selected-image 2>&1)"; then
      log "  selected-image: $out"
    else
      log "  selected-image: (unavailable)"
    fi

    if command -v rauc >/dev/null 2>&1; then
      log "  RAUC status:"
      rauc status --detailed 2>&1 | while IFS="" read -r line; do
        log "    $line"
      done
    fi

    log "Reboot to activate.  If the new slot fails to boot, SteamOS will"
    log "automatically fall back to slot $FL_CURRENT."
  else
    die "Flashless install failed"
  fi
}

_backend_reboot() {
  [[ $EUID -eq 0 ]] || {
    log_error reboot permission-error "Reboot action requires root."
    exit 1
  }

  # Detect available slots
  local -a options=()
  local slot_a="" slot_b=""

  while IFS=' ' read -r dev label; do
    case "$label" in
      rootfs-A) slot_a="$dev" ;;
      rootfs-B) slot_b="$dev" ;;
    esac
  done < <(lsblk -rno PATH,PARTLABEL 2>/dev/null | awk '$2 == "rootfs-A" || $2 == "rootfs-B"')

  [[ -n "$slot_a" ]] && options+=("A" "Root A ($slot_a)")
  [[ -n "$slot_b" ]] && options+=("B" "Root B ($slot_b)")

  if [[ ${#options[@]} -eq 0 ]]; then
    log_error reboot no-slots "No root partitions found."
    exit 1
  fi

  local selected
  if command -v yad >/dev/null 2>&1 && [[ -n "${DISPLAY:-}" ]]; then
    selected="$(yad --list \
      --title="Boot Selector" \
      --text="Select which root to boot into on next restart:" \
      --column="Slot" --column="Device" \
      --width=400 --height=200 \
      --selectable-rows \
      --print-column=1 \
      "${options[@]}" 2>/dev/null)" || exit 0
    selected="$(echo "$selected" | tr -d '|' | tr -d '\n' | xargs)"
  else
    local -a slot_labels=()
    [[ -n "$slot_a" ]] && slot_labels+=("A")
    [[ -n "$slot_b" ]] && slot_labels+=("B")

    echo ""
    echo "Reboot to which slot?"
    local idx=0
    [[ -n "$slot_a" ]] && echo "  $((++idx))) Root A ($slot_a)"
    [[ -n "$slot_b" ]] && echo "  $((++idx))) Root B ($slot_b)"
    read -rp "Choice: " choice
    if [[ "$choice" =~ ^[0-9]+$ ]] && ((choice >= 1 && choice <= ${#slot_labels[@]})); then
      selected="${slot_labels[$((choice - 1))]}"
    else
      exit 0
    fi
  fi

  local conf_file="/esp/SteamOS/conf/${selected}.conf"
  if [[ ! -f "$conf_file" ]]; then
    log_error reboot boot-config-missing "Boot config not found: $conf_file"
    exit 1
  fi

  local now
  now="$(date -u +%Y%m%d%H%M%S)"

  sed -i "s/^boot-requested-at:.*/boot-requested-at: $now/" "$conf_file" \
    || {
      log_error reboot boot-request-failed "Failed to set boot-requested-at for $selected"
      exit 1
    }

  # Clear the other slot
  local other="A"
  [[ "$selected" == "A" ]] && other="B"
  local other_conf="/esp/SteamOS/conf/${other}.conf"
  [[ -f "$other_conf" ]] \
    && sed -i "s/^boot-requested-at:.*/boot-requested-at: 0/" "$other_conf" 2>/dev/null

  echo "Boot slot set: $selected will boot on next restart"
}

# ---------------------------------------------------------------------------
# Rebuild (repatch) backend — reconcile NVIDIA driver into another partition
# set after an OS update.
# ---------------------------------------------------------------------------
_load_rebuild_libs() {
  # shellcheck source=lib/library-loader.sh
  source "$BACKEND_DIR/library-loader.sh"
  # shellcheck source=lib/pipelines/pipeline_rebuild.sh
  source "$BACKEND_DIR/pipelines/pipeline_rebuild.sh"
  load_workflow_libs "repatch" "$BACKEND_DIR"
}

_backend_cleanup() {
  [[ $EUID -eq 0 ]] || die "Cleanup action requires root."

  # shellcheck source=lib/common.sh
  source "$BACKEND_DIR/common.sh"
  # shellcheck source=lib/protected.sh
  source "$BACKEND_DIR/protected.sh"
  # shellcheck source=lib/mounts.sh
  source "$BACKEND_DIR/mounts.sh"
  # shellcheck source=lib/pipeline_init.sh
  source "$BACKEND_DIR/pipeline_init.sh"

  # Initialize structured logging for cleanup
  mkdir -p "/home/.steamos-build/logs/${BUILD_ID}" 2>/dev/null || true
  local _console_level="info"
  if ((DEBUG)); then
    _console_level="debug"
  elif ((VERBOSE)); then
    _console_level="debug"
  fi

  log_init \
    --log-file "/home/.steamos-build/logs/${BUILD_ID}/cleanup.jsonl" \
    --console-level "$_console_level"

  local state_root="${HOME}/.steamos-build/ledger"
  local run_id="${CLEANUP_RUN_ID:-}"
  local purge="${CLEANUP_PURGE:-0}"

  ensure_steamos_build_dirs

  # If --run-id specified, clean only that run
  if [[ -n "$run_id" ]]; then
    local run_dir="$state_root/runs/$run_id"
    [[ -d "$run_dir" ]] || die "Run not found: $run_id"
    [[ -f "$run_dir/manifest" ]] || die "Run has no manifest: $run_id"

    local run_state
    run_state="$(grep -m1 '^run_state' "$run_dir/manifest" 2>/dev/null | cut -f2)" || run_state=""

    log "Cleaning run $run_id (state=$run_state)"

    case "$run_state" in
      ACTIVE | RECOVERING | BLOCKED)
        # If the build process is still alive, enter its mount namespace
        # to perform cleanup where the mounts are actually visible.
        if cleanup_ledger_pid_alive "$run_dir/manifest"; then
          if cleanup_enter_build_namespace "$run_dir/manifest"; then
            log "Run $run_id cleaned via namespace entry"
            log "Cleanup complete: 1 cleaned, 0 failed, 0 already clean"
            return 0
          else
            warn "Run $run_id: namespace cleanup failed — build alive but nsenter failed"
            warn "  Manual cleanup may be required"
            log "Cleanup complete: 0 cleaned, 1 failed, 0 already clean"
            return 1
          fi
        fi
        # Build process is dead — proceed with init-namespace recovery
        if cleanup_recover "$run_dir"; then
          log "Run $run_id cleaned successfully"
          log "Cleanup complete: 1 cleaned, 0 failed, 0 already clean"
          return 0
        else
          warn "Run $run_id cleanup incomplete — some resources may still be in use"
          log "Cleanup complete: 0 cleaned, 1 failed, 0 already clean"
          return 1
        fi
        ;;
      CLEAN)
        log "Run $run_id is already CLEAN"
        safe_rmdir "$run_dir" 2>/dev/null || true
        log "Removed CLEAN run directory"
        ;;
      *)
        warn "Unknown run state: $run_state"
        ;;
    esac
    log "Cleanup complete: 0 cleaned, 0 failed, 0 already clean"
    return 0
  fi

  # No --run-id: clean ALL stale runs
  if [[ ! -d "$state_root/runs" ]]; then
    log "No runs directory found — nothing to clean"
    return 0
  fi

  # --- Pre-cleanup state report ---
  local report_total=0 report_active=0 report_recovering=0 report_blocked=0 report_clean=0 report_corrupt=0
  local run_dir
  for run_dir in "$state_root/runs"/*/; do
    [[ -d "$run_dir" ]] || continue
    ((++report_total)) || true
    local manifest="$run_dir/manifest"
    if [[ ! -f "$manifest" ]]; then
      ((++report_corrupt)) || true
      continue
    fi
    local _rs
    _rs="$(grep -m1 '^run_state' "$manifest" 2>/dev/null | cut -f2)" || _rs=""
    case "$_rs" in
      ACTIVE) ((++report_active)) || true ;;
      RECOVERING) ((++report_recovering)) || true ;;
      BLOCKED) ((++report_blocked)) || true ;;
      CLEAN) ((++report_clean)) || true ;;
      *) ((++report_corrupt)) || true ;;
    esac
  done

  log " "
  log "=== State Report ==="
  log "  $report_total run(s) found"
  ((report_active)) && log "    $report_active    ACTIVE"
  ((report_recovering)) && log "    $report_recovering    RECOVERING"
  ((report_blocked)) && log "    $report_blocked    BLOCKED"
  ((report_clean)) && log "    $report_clean    CLEAN"
  ((report_corrupt)) && log "    $report_corrupt    CORRUPT/UNKNOWN"
  log " "
  log_debug cleanup run-state "Detailed run state:"
  for run_dir in "$state_root/runs"/*/; do
    [[ -d "$run_dir" ]] || continue
    cleanup_report_run_state "$run_dir"
  done
  log " "

  # --- Proceed with cleanup ---
  local cleaned=0 failed=0 already_clean=0

  for run_dir in "$state_root/runs"/*/; do
    [[ -d "$run_dir" ]] || continue

    local manifest="$run_dir/manifest"
    [[ -f "$manifest" ]] || continue

    local rid
    rid="$(basename "$run_dir")"

    local run_state
    run_state="$(grep -m1 '^run_state' "$manifest" 2>/dev/null | cut -f2)" || run_state=""

    case "$run_state" in
      ACTIVE | RECOVERING | BLOCKED)
        log "Cleaning stale run $rid (state=$run_state)..."
        # If the build process is still alive, enter its mount namespace
        # to perform cleanup where the mounts are actually visible.
        if cleanup_ledger_pid_alive "$manifest"; then
          if cleanup_enter_build_namespace "$manifest"; then
            log "  Run $rid cleaned via namespace entry"
            ((++cleaned)) || true
          else
            warn "  Run $rid: namespace cleanup failed — build alive but nsenter failed"
            warn "    Manual cleanup may be required"
            ((++failed)) || true
          fi
        elif cleanup_recover "$run_dir"; then
          log "  Run $rid cleaned"
          ((++cleaned)) || true
        else
          warn "  Run $rid cleanup incomplete"
          ((++failed)) || true
        fi
        ;;
      CLEAN)
        debug "Run $rid is already CLEAN"
        ((++already_clean)) || true
        if ((purge)); then
          safe_rmdir "$run_dir" 2>/dev/null || true
          debug "  Purged CLEAN run $rid"
        fi
        ;;
      *)
        warn "Run $rid has unknown state: $run_state"
        ;;
    esac
  done

  # --- Post-cleanup state report ---
  log " "
  log_debug cleanup run-state "Detailed run state (post-cleanup):"
  for run_dir in "$state_root/runs"/*/; do
    [[ -d "$run_dir" ]] || continue
    cleanup_report_run_state "$run_dir"
  done

  log " "
  log "Cleanup complete: $cleaned cleaned, $failed failed, $already_clean already clean"

  if ((failed > 0)); then
    return 1
  fi
  return 0
}

_backend_rebuild() {
  [[ $EUID -eq 0 ]] || die "Rebuild action requires root."

  # ── Persistent log setup (must happen before sourcing common.sh) ────────
  PERSIST_LOG_DIR="/home/.steamos-build/logs"
  mkdir -p "$PERSIST_LOG_DIR"

  local run_id
  run_id="$(date +%Y%m%d-%H%M%S)-$$"
  # shellcheck disable=SC2034  # used by failure_snapshot_extra via RUN_LOG
  RUN_LOG="$PERSIST_LOG_DIR/repatch-$run_id.log"

  ln -sfn "$(basename "$RUN_LOG")" \
    "$PERSIST_LOG_DIR/repatch-latest.log"

  # Keep stdout/stderr flowing to the caller, but independently retain
  # everything on the persistent /home filesystem.
  # Save original fds so tee can write to the real console.
  exec 7>&1 8>&2
  exec > >(tee -a "$RUN_LOG" >&7) 2>&1 # lint-ignore: tee-redirect

  # ── Repatch-specific globals (must be set before sourcing common.sh) ────
  # shellcheck disable=SC2034  # read by sourced common.sh
  LOG_TAG="repatch"
  # shellcheck disable=SC2034  # read by sourced common.sh
  LOGGER_TAG="steamos-build-repatch"
  # shellcheck disable=SC2034  # read by sourced common.sh
  LOG_COLOR=0
  CURRENT_STEP="startup"
  # shellcheck disable=SC2034  # read by sourced common.sh
  FAILURE_REPORTED=0

  # May not exist yet if failure happens very early.
  : "${NEWROOT:=}"

  # ── Source libraries ─────────────────────────────────────────────────────
  _load_rebuild_libs
  ensure_steamos_build_dirs

  # ── Failure context functions ────────────────────────────────────────────
  _rebuild_failure_journal_context() {
    printf "partset='%s' kver='%s'\n" \
      "${PARTSET:-unknown}" \
      "${KVER:-unknown}"
  }

  _rebuild_failure_snapshot_extra() {
    local _slot

    # Send a desktop notification to the user about the critical failure.
    _notify_desktop critical \
      "SteamOS update patch failed" \
      "The SteamOS update was cancelled because a critical customization failed.

Failed step: ${CURRENT_STEP:-unknown}

Log: ${RUN_LOG:-unknown}"

    log_debug repatch failure-snapshot "SLOT STATE"
    rauc status --detailed 2>&1 | log_capture_stream repatch debug slot-state || true
    steamos-bootconf list-images 2>&1 | log_capture_stream repatch debug slot-state || true

    for _slot in A B; do
      log_debug repatch failure-snapshot "Slot $_slot config"
      steamos-bootconf --image "$_slot" config \
        --get boot-attempts \
        --get boot-requested-at \
        --get image-invalid \
        --get comment 2>&1 | log_capture_stream repatch debug "slot-$_slot-config" || true
    done

    if [[ -n "${NEWROOT:-}" ]] && mountpoint -q "$NEWROOT" 2>/dev/null; then
      log_debug repatch failure-snapshot "TARGET ROOTFS"
      findmnt "$NEWROOT" 2>&1 | log_capture_stream repatch debug target-rootfs || true
      btrfs filesystem usage "$NEWROOT" 2>&1 | log_capture_stream repatch debug target-rootfs || true

      if [[ -n "${KVER:-}" ]]; then
        log_debug repatch failure-snapshot "TARGET DRIVER STATE"
        chroot "$NEWROOT" dkms status 2>&1 | log_capture_stream repatch debug target-driver-state || true
        chroot "$NEWROOT" pacman -Q nvidia-utils 2>&1 | log_capture_stream repatch debug target-driver-state || true
      fi
    fi
  }

  failure_journal_context() { _rebuild_failure_journal_context; }    # lint-ignore: no-shadow
  failure_snapshot_extra() { _rebuild_failure_snapshot_extra "$@"; } # lint-ignore: no-shadow

  # _notify_desktop URGENCY TITLE BODY
  #   Send a desktop notification to the deck user's Plasma session.
  #   Urgency: "critical" (sticky), "normal" (auto-expires), "low".
  #   Falls back through: notify-send → busctl → log only.
  _notify_desktop() {
    local urgency="${1:-normal}"
    local title="$2"
    local body="$3"

    local user="deck"
    local uid

    uid="$(id -u "$user" 2>/dev/null)" || {
      log "_notify_desktop: cannot resolve uid for $user"
      return 1
    }

    [[ -S "/run/user/$uid/bus" ]] || {
      log "_notify_desktop: no D-Bus session for $user (no /run/user/$uid/bus)"
      return 1
    }

    local icon="dialog-information"
    [[ "$urgency" == "critical" ]] && icon="dialog-error"

    # Prefer notify-send if available.
    if command -v notify-send >/dev/null 2>&1; then
      runuser -u "$user" -- env \
        XDG_RUNTIME_DIR="/run/user/$uid" \
        DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" \
        notify-send \
        --urgency="$urgency" \
        --app-name="SteamOS NVIDIA Patcher" \
        --icon="$icon" \
        "$title" \
        "$body" 2>/dev/null && return 0

      log "_notify_desktop: notify-send failed, falling back to busctl"
    fi

    # Fallback: direct D-Bus call via busctl (part of systemd, always present).
    local urgency_byte=1
    [[ "$urgency" == "critical" ]] && urgency_byte=2
    [[ "$urgency" == "low" ]] && urgency_byte=0

    runuser -u "$user" -- env \
      XDG_RUNTIME_DIR="/run/user/$uid" \
      DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" \
      busctl --user call \
      org.freedesktop.Notifications \
      /org/freedesktop/Notifications \
      org.freedesktop.Notifications \
      Notify \
      "susssasa{sv}" \
      "SteamOS NVIDIA Patcher" \
      0 \
      "$icon" \
      "$title" \
      "$body" \
      0 \
      1 "urgency" "y" "$urgency_byte" \
      2>/dev/null && return 0

    log "_notify_desktop: busctl fallback also failed"
    return 1
  }

  # ── Resolve PARTSET ─────────────────────────────────────────────────────
  PARTSET="${PARTSET:-other}"

  # ── Safety guard: refuse to modify the booted slot ──────────────────────
  local _booted _target_slot
  _booted="$(steamos-bootconf this-image 2>/dev/null || true)"
  _target_slot=""
  case "$PARTSET" in
    other)
      case "$_booted" in
        A) _target_slot=B ;;
        B) _target_slot=A ;;
      esac
      ;;
    A | B) _target_slot="$PARTSET" ;;
  esac

  if [[ -n "$_booted" && -n "$_target_slot" && "$_target_slot" == "$_booted" ]]; then
    die "Refusing to modify the currently booted slot ($_booted). Use 'other' or specify the inactive slot."
  fi

  log "Repatch target: partset=$PARTSET booted=${_booted:-unknown} target=${_target_slot:-unknown}"

  # ── Workspace setup ─────────────────────────────────────────────────────
  # shellcheck disable=SC2034  # read by sourced pipeline_rebuild.sh
  ROOTDEV="/dev/disk/by-partsets/$PARTSET/rootfs"
  # shellcheck disable=SC2034  # read by sourced pipeline_rebuild.sh
  EFIDEV="/dev/disk/by-partsets/$PARTSET/efi"

  NEWROOT="$(mktemp -d /tmp/repatch-root.XXXXXX)"
  # SteamOS /home is ext4 with casefold enabled, which OverlayFS rejects as an
  # upperdir.  Build inside a temporary plain-ext4 loopback filesystem stored on
  # /home, where there is enough space for DKMS/toolchain work.
  # shellcheck disable=SC2034  # read by sourced pipeline_rebuild.sh
  WORKIMG=/home/.steamos-build-work.img
  # shellcheck disable=SC2034  # read by sourced pipeline_rebuild.sh
  WORK="$(mktemp -d /tmp/repatch-work.XXXXXX)"
  # shellcheck disable=SC2034  # read by sourced pipeline_rebuild.sh
  WORK_LOOPDEV=""

  cleanup_set_workspace "$NEWROOT" 2>/dev/null || true

  # ── Register and run pipeline ───────────────────────────────────────────
  register_rebuild_pipeline
  register_rebuild_cleanup

  # Chain tee flush into the EXIT trap that register_rebuild_cleanup just set.
  # Without this, the tee subprocess would be orphaned on exit.
  local _existing_exit_trap
  _existing_exit_trap="$(trap -p EXIT | sed "s/^trap -- '//;s/' EXIT$//")"
  # shellcheck disable=SC2064  # intentional: expand _existing_exit_trap at set-time for trap chaining
  trap "${_existing_exit_trap:+$_existing_exit_trap; }exec 1>&7 2>&8 7>&- 8>&-; wait" EXIT

  # Ledger: recover from previous run, then initialize
  # shellcheck disable=SC2119  # pipeline_recover uses default state_root
  pipeline_recover || warn "Ledger recovery failed — proceeding without crash recovery"
  pipeline_init "" "/home/.steamos-build" || warn "Ledger initialization failed — proceeding without crash recovery"

  # Run the pipeline
  if run_pipeline; then
    # Pipeline succeeded — summarize results
    local _ok_count=0 _fail_count=0 _skip_count=0
    for _entry in "${PATCH_RESULTS[@]}"; do
      local _name _status _detail
      IFS='|' read -r _name _status _detail <<<"$_entry"
      if [[ "$_status" == "ok" ]]; then
        ((++_ok_count)) || true
      elif [[ "$_status" == "skip" ]]; then
        ((++_skip_count)) || true
      else
        ((++_fail_count)) || true
      fi
    done

    if ((_fail_count == 0)); then
      step "OK — $PARTSET is NVIDIA-ready (${KVER:-unknown})"
      exit 0
    fi

    # Some optional patches failed but slot is bootable
    warn ""
    warn "============================================================"
    warn " SteamOS NVIDIA Repatch: COMPLETED WITH WARNINGS"
    warn "============================================================"
    warn ""
    warn "SteamOS update installed successfully, but some optional"
    warn "patches failed.  The updated slot remains bootable."
    warn ""
    local _warn_failed_list=""
    warn "Patch results:"
    for _entry in "${PATCH_RESULTS[@]}"; do
      local _name _status _detail
      IFS='|' read -r _name _status _detail <<<"$_entry"
      if [[ "$_status" == "ok" ]]; then
        warn "  ✓ $_name"
      elif [[ "$_status" == "skip" ]]; then
        warn "  ○ $_name — skipped: $_detail"
      else
        warn "  ✗ $_name — $_detail"
        _warn_failed_list+="$_name, "
      fi
    done
    _warn_failed_list="${_warn_failed_list%, }"
    warn ""
    warn "Full log: $RUN_LOG"
    warn "============================================================"
    warn ""

    _notify_desktop normal \
      "SteamOS NVIDIA: patch warnings" \
      "The SteamOS update succeeded, but some optional patches failed: $_warn_failed_list.

Your system is bootable. See the repatch log for details:
$RUN_LOG"

    exit 10
  else
    # Pipeline failed — critical failure
    warn ""
    warn "============================================================"
    warn " SteamOS NVIDIA Repatch: CRITICAL FAILURE"
    warn "============================================================"
    warn ""
    warn "A critical customization failed. The staged OS update has been"
    warn "cancelled to prevent an unbootable system."
    warn ""
    warn "Full log: $RUN_LOG"
    warn "============================================================"
    warn ""

    _notify_desktop critical \
      "SteamOS NVIDIA: patch failed" \
      "The SteamOS update was cancelled because a critical customization failed.

Your system is unchanged. See the repatch log for details:
$RUN_LOG"

    exit 1
  fi
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------
case "$ACTION" in
  build)
    _backend_build
    ;;
  flash)
    _load_flash_libs
    _backend_flash
    ;;
  flashless)
    _backend_flashless
    ;;
  list-images)
    _flash_discover_images
    ;;
  list-devices)
    _load_flash_libs
    flash_scan_devices
    ;;
  is-system-disk)
    [[ -n "$TARGET_DEV" ]] || {
      log_error backend dispatch-error "--device is required"
      exit 2
    }
    _load_flash_libs
    flash_is_system_disk "$TARGET_DEV"
    ;;
  preflight)
    [[ -n "$IMG" ]] || {
      log_error backend dispatch-error "--image is required"
      exit 2
    }
    [[ -n "$TARGET_DEV" ]] || {
      log_error backend dispatch-error "--device is required"
      exit 2
    }
    _load_flash_libs
    IMG="$(readlink -f "$IMG")"
    flash_preflight "$IMG" "$TARGET_DEV"
    ;;
  live)
    _backend_live
    ;;
  validate)
    _backend_validate
    ;;
  reboot)
    _backend_reboot
    ;;
  rebuild)
    _backend_rebuild
    ;;
  cleanup)
    _backend_cleanup || exit $?
    ;;
  *)
    log_error backend dispatch-error "Unknown action: $ACTION"
    _backend_usage >&2
    exit 2
    ;;
esac
