#!/bin/bash
#
# steamos-nvidia-installer — lib/gui-helpers.sh
# YAD GUI helpers: image scanning, config I/O, dialog wrappers.
# Sourced by gui.sh — do not run directly.

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "lib/gui-helpers.sh is a library — source it from gui.sh, not run directly." >&2
  exit 1
fi

# ---- dependency check ----
gui_check_deps() {
  local missing=()
  for cmd in yad lsblk python3; do
    command -v "$cmd" >/dev/null || missing+=("$cmd")
  done
  if [[ ${#missing[@]} -gt 0 ]]; then
    yad --text="Missing required tools: ${missing[*]}" --button="OK:0" 2>/dev/null
    return 1
  fi
}

# ---- image scanning ----

# Scan for existing SteamOS images in common locations.
# Prints one path per line, sorted by modification time (newest first).
gui_scan_images() {
  local script_dir="${1:-.}"
  local search_dirs=(
    "$script_dir"
    "$script_dir/.nvidia-usb-work"
    "/dev/shm/nvidia-build"
    "$HOME/Downloads"
    "$HOME/Downloads/.nvidia-usb-work"
    "/tmp"
  )
  local imgs=()
  for d in "${search_dirs[@]}"; do
    [[ -d "$d" ]] || continue
    while IFS= read -r f; do
      imgs+=("$f")
    done < <(find "$d" -maxdepth 1 \( \
      -name '*.img' -o -name '*.img.bz2' -o -name '*.img.gz' \
      -o -name '*.img.xz' -o -name '*.img.zst' \
    \) -type f \
      ! -name '*.building' \
      ! -name 'overlay-work.img' \
      ! -name 'rootfs-writable.img' \
      ! -name '*-nvidia-usbinstall.img.building' \
      2>/dev/null)
  done
  printf '%s\n' "${imgs[@]}" | sort -u
}

# Get human-readable image info: "filename (size)"
gui_image_info() {
  local img="$1"
  local size
  size="$(du -h "$img" 2>/dev/null | cut -f1)"
  echo "$(basename "$img") ($size)"
}

# ---- config I/O ----

# Write a config file from current variables.
#   gui_write_config PATH
gui_write_config() {
  local conf="$1"
  cat > "$conf" <<EOF
# steamos-nvidia-installer config — generated by gui.sh
IMG="$IMG"
DRIVER_SPEC="$DRIVER_SPEC"
UPDATE_MODE="$UPDATE_MODE"
ADD_INSTALLER=$ADD_INSTALLER
TRIM_CUDA=$TRIM_CUDA
BUILD_HW_SUPPORT=$BUILD_HW_SUPPORT
THUNDERBOLT=$THUNDERBOLT
DEFAULT_SESSION="$DEFAULT_SESSION"
ROOTFS_SIZE="$ROOTFS_SIZE"
SKIP_SIG=$SKIP_SIG
FIX_KEYRING=$FIX_KEYRING
WORKDIR="$WORKDIR"
WORKDIR_LOCATION="$WORKDIR_LOCATION"
EOF
}

# Read a config file (source it).
#   gui_read_config PATH
gui_read_config() {
  local conf="$1"
  [[ -f "$conf" ]] || { echo "Config not found: $conf" >&2; return 1; }
  source "$conf"
}

# ---- YAD dialog wrappers ----

# Simple info dialog
gui_info() {
  local title="$1" text="$2"
  yad --title="$title" --text="$text" --button="OK:0" --width=500 2>/dev/null
}

# Simple error dialog
gui_error() {
  local text="$1"
  yad --title="Error" --text="<b>Error:</b>\n\n$text" --button="OK:0" --width=400 2>/dev/null
}

# Simple warning dialog
gui_warning() {
  local title="$1" text="$2"
  yad --title="$title" --text="<b>Warning:</b>\n\n$text" --button="OK:0" --width=500 2>/dev/null
}

# Question dialog.  Returns 0 for OK, 1 for Cancel.
gui_question() {
  local title="$1" text="$2" ok_label="${3:-OK}" cancel_label="${4:-Cancel}"
  yad --title="$title" --text="$text" \
    --button="$cancel_label:1" --button="$ok_label:0" \
    --width=500 2>/dev/null
}

# Mode selection dialog.  Sets GUI_MODE to "build" or "flash".
gui_mode_dialog() {
  local has_images="$1"
  local text="<b>SteamOS NVIDIA Installer</b>\n\n"
  text+="What would you like to do?"

  if [[ "$has_images" == "yes" ]]; then
    text+="\n\n<i>Existing images were found in common locations.</i>"
  fi

  GUI_MODE="$(yad --list --title="SteamOS NVIDIA Installer" \
    --text="$text" \
    --column="Action" --column="Description" \
    --width=450 --height=300 \
    --print-column=1 \
    build "Build a new SteamOS NVIDIA image" \
    flash "Flash an existing image to USB" \
    quit "Exit" \
  2>/dev/null)" || GUI_MODE="quit"

  # YAD appends a trailing pipe
  GUI_MODE="${GUI_MODE%|}"
}

# Build options form.  Populates build config variables.
gui_build_form() {
  local script_dir="$1"
  local detected_img="$2"

  local result rc
  while true; do
    result="$(yad --form --title="Build Options" \
      --text="<b>Configure image build</b>" \
      --width=550 --height=500 \
      --field="Source Image:FL" "$detected_img" \
      --field="Driver Spec:CB" "latest!580!575!570" \
      --field="Update Mode:CB" "selfheal!hold!stock" \
      --field="Include Installer:CHK" TRUE \
      --field="Trim CUDA (saves ~350MB):CHK" FALSE \
      --field="Extra HW Support:CHK" TRUE \
      --field="Thunderbolt Dock Support:CHK" TRUE \
      --field="Boot to Desktop Mode:CHK" FALSE \
      --field="Rootfs Size (MiB):NUM" "10240" \
      --field="Skip Signature Check:CHK" FALSE \
      --field="Fix Keyring:CHK" TRUE \
      --field="Work Directory:" "" \
      --field="Build Location:CB" "auto!ram!disk" \
      --button="Help:2" --button="Build:0" --button="Cancel:1" \
    2>/dev/null)"
    rc=$?

    case $rc in
      2) # Help
        echo "<b>Source Image</b>
  The clean SteamOS OOBE repair image (.img, .bz2, .gz, .xz, .zst).
  Download from Valve's SteamOS recovery page.

<b>Driver Spec</b>
  Which NVIDIA driver to install.
  • latest — whatever current Arch ships (default)
  • 580, 575, 570 — branch prefix; newest build of that branch
  • 580.105.08 — specific version
  • 580.105.08-4 — exact pkgver-pkgrel
  Needs RTX 20xx+ (Turing) for nvidia-open.

<b>Update Mode</b>
  • selfheal — OS updates work; driver is rebuilt for each new
    slot automatically (recommended)
  • hold — OS updates blocked; Steam always shows 'up to date'
  • stock — normal updates; driver is lost on OS update

<b>Include Installer</b>
  Adds a one-click 'Install SteamOS (NVIDIA)' desktop icon
  to the USB image. Lets you install to an internal disk.

<b>Trim CUDA</b>
  Removes CUDA/OpenCL/NVVM/OptiX libs (~350 MB smaller).
  Only needed if you won't use CUDA workloads.

<b>Extra HW Support</b>
  Installs upstream linux-firmware (replaces Valve's Steam Deck
  subset — needed for Intel NPU, AMD dGPU, WiFi, etc. on generic
  hardware), libratbag (Logitech mice), libfprint (fingerprint
  readers), and Logitech HID kernel modules from source.
  Requires network during build.

<b>Thunderbolt Dock Support</b>
  Installs PCI rescan udev rules and enables bolt daemon
  for Thunderbolt/USB4 docks.

<b>Boot to Desktop Mode</b>
  Default to Plasma desktop instead of gamescope/Steam.

<b>Rootfs Size</b>
  Size of the root partitions in MiB. Valve default: 5120.
  Increase if you need more space for extra packages.

<b>Skip Signature Check</b>
  Disable pacman signature verification in the build chroot.
  Use if the image's keyring is too old.

<b>Fix Keyring</b>
  Force-initialize the pacman keyring with fresh keys.
  Use if signature checks fail despite valid packages.

<b>Work Directory</b>
  Where to store build artifacts. Leave blank for auto.
  Needs ~3x the image size free.

<b>Build Location</b>
  • auto — prefer RAM if enough free, otherwise disk
  • ram — force /dev/shm (fast, needs ~24 GB free)
  • disk — force same directory as output image
" | yad --text-info --title="Build Options Help" \
        --width=550 --height=600 \
        --fontname="sans 10" \
        --wrap \
        --button="Close:0" 2>/dev/null
        ;;
      0) # Build
        break
        ;;
      *) # Cancel or closed
        return 1
        ;;
    esac
  done

  # Parse pipe-separated result
  IFS='|' read -r IMG DRIVER_SPEC UPDATE_MODE ADD_INSTALLER TRIM_CUDA \
    BUILD_HW_SUPPORT THUNDERBOLT DEFAULT_SESSION ROOTFS_SIZE SKIP_SIG FIX_KEYRING WORKDIR WORKDIR_LOCATION <<< "$result"

  # Normalize booleans (YAD returns TRUE/FALSE)
  [[ "$ADD_INSTALLER" == "TRUE" ]] && ADD_INSTALLER=1 || ADD_INSTALLER=0
  [[ "$TRIM_CUDA" == "TRUE" ]] && TRIM_CUDA=1 || TRIM_CUDA=0
  [[ "$BUILD_HW_SUPPORT" == "TRUE" ]] && BUILD_HW_SUPPORT=1 || BUILD_HW_SUPPORT=0
  [[ "$THUNDERBOLT" == "TRUE" ]] && THUNDERBOLT=1 || THUNDERBOLT=0
  [[ "$DEFAULT_SESSION" == "TRUE" ]] && DEFAULT_SESSION="desktop" || DEFAULT_SESSION=""
  [[ "$SKIP_SIG" == "TRUE" ]] && SKIP_SIG=1 || SKIP_SIG=0
  [[ "$FIX_KEYRING" == "TRUE" ]] && FIX_KEYRING=1 || FIX_KEYRING=0

  # Clean up rootfs size (strip decimal from YAD num widget)
  ROOTFS_SIZE="${ROOTFS_SIZE%%.*}"
}

# Flash image selector dialog.  Sets FLASH_IMG.
gui_flash_select_image() {
  local script_dir="$1"
  shift
  local images=("$@")

  if [[ ${#images[@]} -eq 0 ]]; then
    # No auto-detected images — use file chooser
    FLASH_IMG="$(yad --file --title="Select Image" \
      --text="No images auto-detected.  Select a SteamOS image file." \
      --file-filter="Images (*.img *.img.bz2 *.img.gz *.img.xz *.img.zst) | *.img *.img.bz2 *.img.gz *.img.xz *.img.zst" \
      --width=600 \
    2>/dev/null)" || return 1
    FLASH_IMG="${FLASH_IMG%|}"
  elif [[ ${#images[@]} -eq 1 ]]; then
    FLASH_IMG="${images[0]}"
  else
    # Multiple images — let user pick
    local list_args=()
    for img in "${images[@]}"; do
      list_args+=("$(gui_image_info "$img")" "$img")
    done
    FLASH_IMG="$(yad --list --title="Select Image" \
      --text="Multiple images found.  Select one to flash." \
      --column="Image" --column="Path" \
      --width=700 --height=400 \
      --print-column=2 \
      --selectable-rows \
      "${list_args[@]}" \
    2>/dev/null)" || return 1
    FLASH_IMG="${FLASH_IMG%|}"
  fi

  [[ -n "$FLASH_IMG" && -f "$FLASH_IMG" ]] || return 1
}

# Flash device selector dialog.  Sets FLASH_DEV.
gui_flash_select_device() {
  local device_list
  device_list="$(flash_scan_devices)"

  [[ -n "$device_list" ]] || {
    gui_error "No USB devices found.\n\nPlug in a USB stick and try again."
    return 1
  }

  local rows=()
  while IFS=$'\t' read -r dev size tran model tag; do
    local type_label="Internal"
    [[ "$tag" == "[removable]" ]] && type_label="Removable"
    rows+=("$dev" "$size" "$model" "$tran" "$type_label")
  done <<< "$device_list"

  local img_info
  img_info="$(gui_image_info "$FLASH_IMG")"

  FLASH_DEV="$(yad --list \
    --title="Select Target Device" \
    --text="Select the target USB device.\n\nImage: $img_info\n\n<b>ALL DATA ON THE SELECTED DEVICE WILL BE DESTROYED.</b>" \
    --column="Device" --column="Size" --column="Model" --column="Bus" --column="Type" \
    --width=750 --height=400 \
    --print-column=1 \
    --selectable-rows \
    "${rows[@]}" \
  2>/dev/null)" || return 1
  FLASH_DEV="${FLASH_DEV%|}"
  FLASH_DEV="$(echo "$FLASH_DEV" | tr -d ' ')"

  [[ -n "$FLASH_DEV" && -b "$FLASH_DEV" ]] || return 1
}

# Flash confirmation dialog.  Returns 0 to proceed.
gui_flash_confirm() {
  local img_info dev_size
  img_info="$(gui_image_info "$FLASH_IMG")"
  dev_size="$(flash_device_size "$FLASH_DEV")"

  # Check for system disk
  if flash_is_system_disk "$FLASH_DEV"; then
    gui_warning "Warning: System Disk" \
      "<b>$FLASH_DEV appears to be the disk you are running from.</b>\n\nIf this is your recovery USB, the OS is loaded into RAM so flashing is safe.\n\nIf this is your internal drive, <b>DO NOT proceed</b>."
    return 1
  fi

  gui_question "Confirm Flash" \
    "<b>About to flash:</b>\n\n  $img_info\n\n<b>To:</b>\n\n  $FLASH_DEV ($dev_size)\n\n<b>This PERMANENTLY DESTROYS all data on $FLASH_DEV.</b>\n\nThis cannot be undone." \
    "Flash" "Cancel"
}

# Build confirmation dialog.  Returns 0 to proceed.
gui_build_confirm() {
  local update_desc
  case "$UPDATE_MODE" in
    selfheal) update_desc="Self-healing (recommended)" ;;
    hold)     update_desc="Hold updates" ;;
    stock)    update_desc="Stock (driver removed on update)" ;;
  esac

  gui_question "Confirm Build" \
    "<b>Build configuration:</b>\n\n  Source: $(basename "$IMG")\n  Driver: $DRIVER_SPEC\n  Updates: $update_desc\n  Installer: $([ "$ADD_INSTALLER" -eq 1 ] && echo yes || echo no)\n  Trim CUDA: $([ "$TRIM_CUDA" -eq 1 ] && echo yes || echo no)\n  HW Support: $([ "$BUILD_HW_SUPPORT" -eq 1 ] && echo yes || echo no)\n  Rootfs: ${ROOTFS_SIZE} MB\n  Build Location: $WORKDIR_LOCATION\n\n<b>This will build a new SteamOS NVIDIA image.</b>" \
    "Build" "Cancel"
}

# Progress log window.  Tails a log file in real time.
#   gui_progress_log TITLE LOGFILE [PID]
gui_progress_log() {
  local title="$1" logfile="$2" pid="${3:-}"

  if [[ -n "$pid" ]]; then
    # Tail the log and watch for the process to finish
    ( tail -f "$logfile" 2>/dev/null &
      TAIL_PID=$!
      wait "$pid" 2>/dev/null
      kill "$TAIL_PID" 2>/dev/null
    ) | yad --text-info --title="$title" \
        --width=800 --height=500 \
        --fontname="monospace" \
        --wrap --tail \
        --button="Close:0" \
        --tail 2>/dev/null
  else
    yad --text-info --title="$title" \
      --width=800 --height=500 \
      --fontname="monospace" \
      --wrap --tail \
      --button="Close:0" \
      < "$logfile" 2>/dev/null
  fi
}

# Success dialog.
gui_done() {
  local title="$1" msg="$2"
  yad --title="$title" --text="$msg" --button="OK:0" --width=500 2>/dev/null
}
