name: Shell Checks

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run all lints
        run: tools/run_linting.sh
